spring.application.name=inventorydetail

#REST API
REQRES_USER_URL=https://reqres.in/api/users

# create and drop table, good for testing, production set to none or comment it
#spring.jpa.hibernate.ddl-auto=create-drop

#setting embedded tomcat server port for spring boot app
server.port=8085

#logging.pattern.correlation=[${spring.application.name:},%X{traceId:-},%X{spanId:-}] 
#logging.include-application-name=false

spring.cache.redis.time-to-live=3600

# H2 database configuration
#spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.url=jdbc:h2:file:./data/testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
