spring.application.name=inventorydetail

spring.jpa.hibernate.ddl-auto=update

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/koshelidb
spring.datasource.username=root
spring.datasource.password=IamtheKing89
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql:true

#REST API
REQRES_USER_URL=https://reqres.in/api/users

# create and drop table, good for testing, production set to none or comment it
#spring.jpa.hibernate.ddl-auto=create-drop

#setting embedded tomcat server port for spring boot app
server.port=8085

#logging.pattern.correlation=[${spring.application.name:},%X{traceId:-},%X{spanId:-}] 
#logging.include-application-name=false

spring.cache.redis.time-to-live=3600